// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVcldyDQt5jBpWtOsVUciS1eYemG0AStU',
    appId: '1:75025842864:web:5cdc499c0e65418fa2f175',
    messagingSenderId: '75025842864',
    projectId: 'latsify-5a586',
    authDomain: 'latsify-5a586.firebaseapp.com',
    storageBucket: 'latsify-5a586.appspot.com',
    measurementId: 'G-31N2NM69RH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqwnYNSlVtfLReybNMbRM0fyM4hKgLgUo',
    appId: '1:75025842864:android:4246d690a61d7327a2f175',
    messagingSenderId: '75025842864',
    projectId: 'latsify-5a586',
    storageBucket: 'latsify-5a586.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA02ZDSKQA4e3QzuySPd9oyPKr4QRs0kA8',
    appId: '1:75025842864:ios:dfd909e64c104a5aa2f175',
    messagingSenderId: '75025842864',
    projectId: 'latsify-5a586',
    storageBucket: 'latsify-5a586.appspot.com',
    iosBundleId: 'com.example.schoolApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA02ZDSKQA4e3QzuySPd9oyPKr4QRs0kA8',
    appId: '1:75025842864:ios:dfd909e64c104a5aa2f175',
    messagingSenderId: '75025842864',
    projectId: 'latsify-5a586',
    storageBucket: 'latsify-5a586.appspot.com',
    iosBundleId: 'com.example.schoolApp',
  );
}
